version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    networks:
      - backing-services

networks: 
  backing-services:
    driver: bridge