---
name: Checks

on: [push]

jobs:
  tests:
    name: Teste
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Instalar Poetry
        run: |
          ls $GITHUB_WORKSPACE
          pip install poetry

      - name: Instalar o python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar pytest
        run : |
          poetry add pytest
          poetry add python-decouple

      - name: Criar arquivo .env
        run: |
          echo "TOKEN_GITHUB=${{ secrets.TOKEN_GITHUB }}" >> .env
          pwd
          cat .env

      - name: Testes
        env:
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
        run : |
          # export $(cat .env | xargs) 
          poetry run pytest --cov
          poetry run coverage xml
          poetry run coverage html
