---
name: Checks

on: [push]

jobs:
  tests:
    name: Teste
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Instalar Poetry
        run: |
          ls $GITHUB_WORKSPACE
          pip install poetry

      - name: Instalar o python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar pytest
        run : |
          poetry add pytest
          poetry add python-decouple

      - name: Criar arquivo .env
        run: |
          # echo "BRIDA_USER=${{ secrets.BRIDA_USER }}" >> .env
          echo "BRIDA_TOKEN=${{ secrets.BRIDA_TOKEN }}" >> .env

      - name: Testes
        run : |
          # export $(cat .env | xargs) 
          poetry run pytest --cov
